"""empty message

Revision ID: 3b232e0f9613
Revises: e3313465ed80
Create Date: 2025-05-25 23:28:09.158634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b232e0f9613'
down_revision = 'e3313465ed80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['birth_year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
